### ISSUE TITLE
✨ Column to Column difference check

### ISSUE THREAD

**Issue by benrutter** [benrutter/wimsey#10]
Cross column comparisons are often tricky in data test frameworks, but there's no particular reason that something like this:
```yaml
first_column: column_a
second_column: column_b
test: average_column_difference_should
be_less_that: 23
```
Shouldn't be possible - implementing it would involve adapting code to make writing these kind of tests smoother and it'd be potentially invaluable for datasets where:

- One column should *always be less* than another column
- One column should be somewhere around a certain factor bigger than the other column etc
