### ISSUE TITLE
Additional column comparison checks

### ISSUE THREAD

**Issue by benrutter** [benrutter/wimsey#27]
At the moment, testing the average ratio and difference between columns is in place, which is handy. But would be useful to have some more "row specific" checks, where a ratio should never stray outside certain margins. I.e if you knew `col_b` should be more than 3 times `col_a` you might have:

```yaml
- test: max_ratio_between_columns_should
  column: col_a
  other_column: col_b
  be_less_than_or_equal_to: 3
```

I think the nice polars/narwhal's API should make this pretty simple, ideally include:

- max_ratio_between_columns_should
- min_ratio_between_columns_should
- max_difference_between_columns_should
- min_difference_between_columns_should
